spring.application.name=EventAccounting
spring.datasource.url=jdbc:postgresql://localhost:5432/events_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
debug=true
spring.jpa.hibernate.ddl-auto=update

